# Generated by Django 6.0 on 2025-12-24 07:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_path', models.CharField(help_text='Physical path on disk', max_length=512, unique=True)),
                ('hash_md5', models.CharField(db_index=True, max_length=32, unique=True)),
                ('captured_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_live_photo', models.BooleanField(default=False)),
                ('video_path', models.CharField(blank=True, help_text='Path to companion video', max_length=512, null=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('size', models.PositiveBigIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-captured_at', '-created_at'],
                'indexes': [models.Index(fields=['captured_at'], name='photos_phot_capture_41834e_idx'), models.Index(fields=['hash_md5'], name='photos_phot_hash_md_ff084d_idx')],
            },
        ),
    ]
