# Generated by Django 6.0 on 2025-12-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='embedding_data',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
