# Generated by Django 6.0 on 2025-12-24 08:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_photo_embedding_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='库名称', max_length=100)),
                ('path', models.CharField(help_text='本地目录绝对路径', max_length=512, unique=True)),
                ('last_scanned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '照片库',
                'verbose_name_plural': '照片库',
            },
        ),
    ]
