# Generated by Django 6.0 on 2025-12-24 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_library'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='processed_files',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='library',
            name='scan_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='library',
            name='scan_status',
            field=models.CharField(choices=[('idle', '空闲'), ('scanning', '扫描中'), ('completed', '已完成'), ('failed', '失败')], default='idle', max_length=20),
        ),
        migrations.AddField(
            model_name='library',
            name='total_files',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
