# Generated by Django 6.0 on 2025-12-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_photo_latitude_photo_location_name_photo_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='scan_status',
            field=models.CharField(choices=[('idle', '空闲'), ('scanning', '扫描中'), ('paused', '已暂停'), ('completed', '已完成'), ('failed', '失败')], default='idle', max_length=20),
        ),
    ]
