# Generated by Django 6.0 on 2025-12-25 06:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_alter_library_scan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='cluster_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='聚类ID'),
        ),
        migrations.AddField(
            model_name='person',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='是否隐藏'),
        ),
        migrations.CreateModel(
            name='Face',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bbox', models.JSONField(verbose_name='边界框')),
                ('embedding', models.BinaryField(blank=True, null=True, verbose_name='特征向量')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faces', to='photos.person', verbose_name='所属人物')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faces', to='photos.photo', verbose_name='照片')),
            ],
            options={
                'verbose_name': '人脸',
                'verbose_name_plural': '人脸',
            },
        ),
    ]
