# Generated by Django 6.0 on 2025-12-25 07:30

import pgvector.django
import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0007_person_cluster_id_person_is_hidden_face'),
    ]

    operations = [
        pgvector.django.VectorExtension(),
        migrations.RemoveField(
            model_name='face',
            name='embedding',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='embedding_data',
        ),
        migrations.AddField(
            model_name='face',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=128, null=True, verbose_name='特征向量'),
        ),
        migrations.AddField(
            model_name='photo',
            name='embedding_data',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=512, null=True, verbose_name='语义向量'),
        ),
    ]
