# Generated by Django 6.0 on 2025-12-25 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0008_alter_face_embedding_alter_photo_embedding_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='face',
            name='prob',
            field=models.FloatField(default=0.0, verbose_name='置信度'),
        ),
    ]
