# Generated by Django 6.0 on 2025-12-25 09:15

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0009_face_prob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='face',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=512, null=True, verbose_name='特征向量'),
        ),
    ]
