# Generated by Django 6.0 on 2025-12-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0010_alter_face_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='face_scanned',
            field=models.BooleanField(db_index=True, default=False, verbose_name='已扫描人脸'),
        ),
    ]
