# Generated by Django 6.0 on 2025-12-26 03:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0011_photo_face_scanned'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('memory_type', models.CharField(choices=[('on_this_day', '那年今日'), ('travel', '旅行足迹'), ('people', '人物重聚'), ('mood', '心境氛围'), ('festival', '节日庆典'), ('custom', '自定义回忆')], max_length=20, verbose_name='回忆类型')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='收藏')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cover', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='photos.photo', verbose_name='封面')),
                ('photos', models.ManyToManyField(related_name='memories', to='photos.photo', verbose_name='关联照片')),
            ],
            options={
                'verbose_name': '回忆',
                'verbose_name_plural': '回忆',
                'ordering': ['-is_favorite', '-created_at'],
            },
        ),
    ]
