# Generated by Django 6.0 on 2025-12-29 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0012_memory'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='ignored_merges',
            field=models.ManyToManyField(blank=True, to='photos.person', verbose_name='忽略的合并建议'),
        ),
    ]
