# Generated by Django 6.0 on 2025-12-29 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0013_person_ignored_merges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='face',
            name='prob',
            field=models.FloatField(db_index=True, default=0.0, verbose_name='置信度'),
        ),
        migrations.AlterField(
            model_name='person',
            name='is_hidden',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否隐藏'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='姓名'),
        ),
    ]
