# Generated by Django 6.0 on 2026-01-04 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0014_alter_face_prob_alter_person_is_hidden_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_starred',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否标星'),
        ),
    ]
