# Generated by Django 6.0 on 2026-01-06 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0016_photo_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='exif_camera_make',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='相机厂商'),
        ),
        migrations.AddField(
            model_name='photo',
            name='exif_camera_model',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='相机型号'),
        ),
        migrations.AddField(
            model_name='photo',
            name='exif_exposure_time',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='快门时间'),
        ),
        migrations.AddField(
            model_name='photo',
            name='exif_f_number',
            field=models.FloatField(blank=True, null=True, verbose_name='光圈'),
        ),
        migrations.AddField(
            model_name='photo',
            name='exif_focal_length',
            field=models.FloatField(blank=True, null=True, verbose_name='焦距'),
        ),
        migrations.AddField(
            model_name='photo',
            name='exif_iso',
            field=models.IntegerField(blank=True, null=True, verbose_name='ISO'),
        ),
        migrations.AddField(
            model_name='photo',
            name='exif_lens_model',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='镜头型号'),
        ),
    ]
