# Generated by Django 6.0 on 2026-01-06 02:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0017_photo_exif_camera_make_photo_exif_camera_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('scan_photos', '扫描照片'), ('process_faces', '人脸识别'), ('cluster_people', '人脸聚类'), ('generate_memories', '生成回忆'), ('cleanup_trash', '清空回收站'), ('update_gps', '更新GPS信息'), ('process_embeddings', '生成语义向量')], max_length=100)),
                ('params', models.JSONField(blank=True, default=dict, verbose_name='参数')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '进行中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20)),
                ('progress', models.IntegerField(default=0, help_text='进度 0-100')),
                ('logs', models.TextField(blank=True, default='')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, default='system', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '维护任务',
                'verbose_name_plural': '维护任务',
                'ordering': ['-created_at'],
            },
        ),
    ]
