# Generated by Django 6.0 on 2026-01-06 02:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0018_maintenancetask'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('scan_photos', '扫描照片'), ('process_faces', '人脸识别'), ('cluster_people', '人脸聚类'), ('generate_memories', '生成回忆'), ('cleanup_trash', '清空回收站'), ('update_gps', '更新GPS信息'), ('process_embeddings', '生成语义向量')], max_length=100, verbose_name='任务类型')),
                ('params', models.JSONField(blank=True, default=dict, verbose_name='参数')),
                ('schedule_type', models.CharField(choices=[('daily', '每天'), ('weekly', '每周'), ('interval', '间隔')], default='daily', max_length=20, verbose_name='调度类型')),
                ('schedule_value', models.CharField(help_text='格式：每天 HH:MM，每周 d HH:MM (0=周一)，间隔 分钟数', max_length=50, verbose_name='调度值')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='上次运行时间')),
                ('next_run_at', models.DateTimeField(blank=True, null=True, verbose_name='下次运行时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '定时任务',
                'verbose_name_plural': '定时任务',
                'ordering': ['created_at'],
            },
        ),
    ]
