# Generated by Django 6.0 on 2026-01-06 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0019_scheduledtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='duration',
            field=models.FloatField(blank=True, null=True, verbose_name='视频时长(秒)'),
        ),
    ]
