# Generated by Django 6.0 on 2026-01-06 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0020_photo_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='face',
            name='timestamp',
            field=models.FloatField(blank=True, null=True, verbose_name='视频时间点(秒)'),
        ),
    ]
